### PR TITLE
fix: replace all PR references with hyperlinks

### PR DESCRIPTION
**Pull request by HashimotoYT**
This pull request, changes regex for create references to issues on release page on website.

It's should fix https://github.com/electron/electronjs.org/issues/1287

/cc @zeke

## Previously replace regex

v1

## New replace regex

v2

### CODE REVIEW

**Comment by zeke** [comment]
Thanks! Can you add tests for this? Let me know if you need help with that.

**Comment by HashimotoYT** [comment]
@zeke, In last commit I'm add test but i think it's not good test solution for now. Release notes takes from fixtures file, and it not test all references.

**Comment by zeke** [comment]
Rather than testing your regex, you should test against the actual results in the `releases` object. Based on the screenshot in https://github.com/electron/electronjs.org/issues/1287, it looks like `#12837` should be a hyperlink, but it's not (yet).

Here's a refactoring of your test:

```js
  it('replaces all PR references like `#123` with hyperlinks', () => {
    const release = releases.find(release => release.version === '3.0.0-beta.1')
    release.body_html.should.contain('<a href="https://github.com/electron/electron/pull/13039">#13039</a>')
    
    // this should pass too but doesn't yet
    // release.body_html.should.contain('<a href="https://github.com/electron/electron/pull/12837">#12837</a>')
  })
```

**Comment by zeke** [comment]
Sorry for the trouble, but can you also back out the changes to `index.json`, `lite.json`, and `readme.md`? Those files are changed by the build script and do not need to be included in this change.

**Comment by HashimotoYT** [comment]
I'm revert e62408626ebbd8b2528097640ce547f9f80d0df7. Also i think needed add `todo` or create issue for update test when bot update all references.

**Comment by HashimotoYT** [comment]
@zeke, any news when this merge?

**Comment by zeke** [comment]
Hey @HashimotoYT sorry for the delay. It looks like this is still not complete. In my comment above https://github.com/electron/releases/pull/18#issuecomment-405392839, I mentioned that this should pass:

```
release1.body_html.should.contain('<a href="https://github.com/electron/electron/pull/12837">#12837</a>')
```

But it doesn't yet.  Please uncomment that line, and update your regex to include a space at the beginning, like `/ #(\d+)/gm`. That should be enough to get this shipped!

**Comment by HashimotoYT** [comment]
@zeke, changes made. Test be passed after build script.

**Comment by zeke** [comment]
Oops forgot to mention: Can you also add `"pretest": "npm run build",` to package.json (before the `test` script), to ensure that the build is run before the tests?

**Comment by HashimotoYT** [comment]
@zeke, Travis failure error:

```
/home/travis/build/electron/releases/node_modules/dotenv-safe/index.js:31
            throw new MissingEnvVarsError(allowEmptyValues, options.path || '.env', example, missing, dotenvResult.error);
            ^
MissingEnvVarsError: The following variables were defined in .env.example but are not present in the environment:
  GITHUB_AUTH_TOKEN
Make sure to add them to .env or directly to the environment.
```

**Comment by zeke** [comment]
Ah.. the build script needs a GitHub token to fetch releases from the GitHub API, but those env vars aren't exposed to PRs from forks on Travis, for security reasons.

🤔I wonder what the best workaround is. Maybe take out the `pretest` script, run the build locally, and commit the change from the build with your PR?

**Comment by HashimotoYT** [comment]
@zeke, conflicts fixed.

**Pull request merged**
