### PR TITLE
Escape HTML in release body when collect

### LINKED ISSUE #17: Sanitize HTML in release body
Example: https://github.com/electron/electronjs.org/issues/1296

`Fixed issue allowing bundles to be selected in <input file="type"> open file dialog.` should not display an input!

The [dompurify](https://ghub.io/dompurify) module might be a good option for this.

### PR DESCRIPTION
**Pull request by pierreneter**
Resolves #17

### CODE REVIEW

**Comment by zeke** [comment]
I think we might actually be able to use `remark-html`'s `sanitize` option for this: https://github.com/remarkjs/remark-html#optionssanitize -- can you give that a try?

**Comment by pierreneter** [comment]
@zeke I had to take a look at this `remark-html` before add `escape-html` and I think it doesn't match with the think we need,

> Compile markdown to HTML with remark.

We don't need compile to HTML, we just need to keep Markdown content body for electron site can parse it to HTML without some HTML tag appears wrong place.

**Comment by zeke** [comment]
> We don't need compile to HTML

We **do** need to compile it to HTML. This module takes care of that with hubdown, and the website renders the HTML. See https://github.com/electron/electronjs.org/blob/9bab575dfb77a39a104287690694075557c380d5/views/releases/index.html#L29

Sorry for the confusion, but this fix may actually need to happen in a different repo: https://github.com/electron/hubdown/blob/master/index.js

**Comment by pierreneter** [comment]
`remark-html` with `sanitize` is done by https://github.com/syntax-tree/hast-util-sanitize

I think it makes HTML cleaner, can see:

https://github.com/syntax-tree/hast-util-sanitize#usage

I parse HTML contents in the content of Markdown body, for example:

```
### Bug Fixes\r\n\r\n* Fixed crashes with natively compiled modules. #13260 \r\n* Mark browser window affinity as experimental. #13295 \r\n* Enabled WebFrame method forwarding in sandboxed renderers (#12538). <a href=\"https://github.com/electron/electron/pull/13076\">#13076</a>\r\n* Fixed issue starting Electron with Node options. <a href=\"https://github.com/electron/electron/pull/13324\">#13324</a>\r\n* Fixed passing the boolean value of enableAutoSize in webContents.setSize(options).  <a href=\"https://github.com/electron/electron/pull/13330\">#13330</a>\r\n* **[SECURITY]**  Added temporal index bounds check for WebRTC. #13305 \r\n\r\n#### macOS\r\n\r\n* Fixed tray title not inverting when highlighted. #13262 \r\n* Fixed to allow lookup of videodecoder service to fix HW video decoding on macOS 10.13. #13275, #13345 \r\n* Fixed issue allowing bundles to be selected in &lt;input file=&quot;type&quot;&gt; open file. #13277 \r\n* Fixed to set mac protocol to none after calling app.removeAsDefaultProtocolClient. #13325 \r\n
```

escape HTML before parsing this content to HTML maybe a big deal.

Or we can try to add `remark-html` to `hubdown` before continuing with this PR.

**Comment by pierreneter** [comment]
But with my way at here. It just work. You can clear your local `index.json` and collect again for check.

**Comment by ckerr** [comment]
I'm closing this PR as part of a bulk-closing of stale PRs that appear to no longer be applicable.

If anyone thinks this PR is still valid and thinks it should be reconsidered, please rebase / update the patch to `master` and open a new PR. Thank you!

**Pull request closed without merging**
